name: Testing
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - develop
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  CAPSULE_LOG: none

jobs:
  test:
    name: Run workflow tests
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/v-met') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.6"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
          - "22.04"
          - "22.10"
          - "23.04"
          - "23.10"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: MillironX/setup-nextflow@octokit-throttling-dist
        with:
          version: ${{ matrix.NXF_VER }}
      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker

  parameters:
    name: Test workflow parameters
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/v-met') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--blast_target classified"
          - "--blast_target unclassified"
          - "--blast_target all"
          - "--kraken2_db ~/kraken2-db"
          - "--skip_qc"
          - "--skip_trimming"
          - "--skip_blast"
        NXF_VER:
          - "21.10.6"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
          - "22.04"
          - "22.10"
          - "23.04"
          - "23.10"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: MillironX/setup-nextflow@octokit-throttling-dist
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Download Kraken2 database
        if: ${{ matrix.parameters == '--kraken2_db ~/kraken2-db' }}
        run: |
          mkdir ~/kraken2-db
          wget -qO- https://genome-idx.s3.amazonaws.com/kraken/k2_viral_20210517.tar.gz | tar xzv -C ~/kraken2-db

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker ${{ matrix.parameters }}

  test_interleaved:
    name: Test Interleaved Reads Workflow
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/v-met') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.6"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
          - "22.04"
          - "22.10"
          - "23.04"
          - "23.10"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: MillironX/setup-nextflow@octokit-throttling-dist
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_interleaved,gh,docker
  test_nanopore:
    name: Run workflow tests
    # Only run on push if this is the develop branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ksumngs/v-met') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.6"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
          - "22.04"
          - "22.10"
          - "23.04"
          - "23.10"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: MillironX/setup-nextflow@octokit-throttling-dist
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Run pipeline with test data
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,gh,docker
