name: Documentation
on:
  - release
  - workflow_dispatch
jobs:
  build:
    name: Sphinx docs to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Python 🐍
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install Sphinx 🇪🇬
        uses: logikal-code/pip-install@v1.0.0
        with:
          requirements: docs/requirements.txt
      - name: Build docs 📝
        run: |
          sphinx-multiversion docs docs/_build
      - name: Collect 🧺
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: |
            docs/_build
      - name: Deploy 🚀
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/_build
          clean: false
