name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          token: ${{ secrets.RELEASE_TOKEN }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
